name: Generate PDF
on:
  push:
    branches: [ pdf ]
    # paths:
    #   - 'doc/**'  # Trigger when docs are updated
    
jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js for mdPDF
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Combine Markdown files
        id: combine_md
        run: |
          echo "# Combined Documentation" > combined.md
          find doc -name "*.md" | sort | xargs cat >> combined.md
          echo "::set-output name=combined_file::combined.md"

      - name: Convert Combined Markdown to PDF
        run: |
           md-to-pdf ${{ steps.combine_md.outputs.combined_file }}

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdfs
          path: combined.pdf
